### NumPy - Numerical Python

- Works primarily on and with arrays. 
- And arrays are homogeneous i.e. hold only ONE data type and that is `numbers.`

In [25]:
import numpy as np #imported numpy as an alias np

In [3]:
#np.__version__

'1.18.1'

### Creating arrays

#### i) From a list

In [4]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [5]:
my_array = np.array(my_list)
my_array

array([1, 2, 3, 4, 5])

#### ii) From np.array()

In [6]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

#### iii) np.arange()

In [7]:
np.arange(start = 0, stop = 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

#### iv) np.linspace

In [12]:
np.linspace(0,10, retstep = True)

(array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
         1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
         2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
         3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
         4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
         5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
         6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
         7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
         8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
         9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ]),
 0.20408163265306123)

In [13]:
np.linspace(0, 10, num = 5, retstep = True)

(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), 2.5)

#### v) np.eye() / np.identity()

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### vi) np.zeros() and np.ones()

In [16]:
np.zeros(4)

array([0., 0., 0., 0.])

In [17]:
np.zeros(shape = (2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones(2)

array([1., 1.])

In [28]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
ones + 4

array([[5., 5., 5.],
       [5., 5., 5.]])

In [22]:
zeros + 5

array([[5., 5., 5.],
       [5., 5., 5.]])

In [23]:
my_list

[1, 2, 3, 4, 5]

In [24]:
my_list + 5 

TypeError: can only concatenate list (not "int") to list

#### vii) np.full()

In [26]:
np.full(shape = 2, fill_value = 5)

array([5, 5])

In [27]:
np.full((2,3), 5)

array([[5, 5, 5],
       [5, 5, 5]])

### Random values

rand - random values are picked from over a uniform distribution i.e. 0(inclusive) to 1 (exclusive) range.

In [31]:
np.random.rand()

0.26391912133354123

In [32]:
np.random.rand(4)

array([0.60806669, 0.65689146, 0.94304297, 0.599931  ])

In [33]:
np.random.rand(3,2)

array([[0.12727233, 0.79841399],
       [0.13286991, 0.17716451],
       [0.46980327, 0.35329853]])

randn - random values are picked from over a normal distribution i.e. mostly between -2 and 2

In [34]:
np.random.randn()

0.5447128932240553

In [35]:
np.random.randn(4)

array([-1.24833729, -0.45029717,  1.23506923,  0.8066764 ])

In [36]:
np.random.randn(2,3)

array([[ 0.70021324, -1.81124792,  1.69850853],
       [ 0.37778008, -0.63057265, -1.0319611 ]])

randint - random `integer` values are picked from over the specified range.

In [37]:
np.random.randint(low = 0, high = 10)

6

In [38]:
np.random.randint(0, 10, size = 3)

array([6, 8, 5])

In [39]:
np.random.randint(0, 20, (3,4))

array([[14,  1,  9,  7],
       [ 7,  4, 11, 18],
       [10,  8, 16, 10]])

.uniform() - similar to `rand` but with more control over the range that values are picked over.

In [40]:
np.random.uniform(low = 50, high = 70, size = 4)

array([57.587883  , 63.61304077, 61.41913671, 56.04451576])

.normal() - similar to `randn` but with more control over the range that values are picked over.

In [41]:
np.random.normal(loc = 50, scale = 5, size = 4)

array([52.57763307, 46.17469586, 48.03006753, 45.59646341])

### Array attributes

In [42]:
my_array = np.random.randint(10, 100, size = 30)
my_array

array([15, 71, 50, 22, 23, 90, 96, 10, 88, 19, 68, 79, 97, 55, 82, 84, 44,
       28, 11, 33, 62, 46, 76, 12, 98, 18, 11, 52, 76, 51])

In [43]:
my_array.shape

(30,)

In [44]:
my_array.ndim

1

In [46]:
my_array.dtype

dtype('int32')

In [47]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [48]:
zeros.dtype

dtype('float64')

### Array methods

In [51]:
my_reshaped_array = my_array.reshape(2,15)
my_reshaped_array

array([[15, 71, 50, 22, 23, 90, 96, 10, 88, 19, 68, 79, 97, 55, 82],
       [84, 44, 28, 11, 33, 62, 46, 76, 12, 98, 18, 11, 52, 76, 51]])

In [52]:
my_reshaped_array.shape

(2, 15)

In [53]:
my_reshaped_array.ndim

2

In [54]:
my_reshaped_array.dtype

dtype('int32')

In [55]:
my_array.reshape(6,5)

array([[15, 71, 50, 22, 23],
       [90, 96, 10, 88, 19],
       [68, 79, 97, 55, 82],
       [84, 44, 28, 11, 33],
       [62, 46, 76, 12, 98],
       [18, 11, 52, 76, 51]])

In [56]:
my_reshaped_array_2 = my_array.reshape(6, -1)
my_reshaped_array_2

array([[15, 71, 50, 22, 23],
       [90, 96, 10, 88, 19],
       [68, 79, 97, 55, 82],
       [84, 44, 28, 11, 33],
       [62, 46, 76, 12, 98],
       [18, 11, 52, 76, 51]])

In [57]:
my_array

array([15, 71, 50, 22, 23, 90, 96, 10, 88, 19, 68, 79, 97, 55, 82, 84, 44,
       28, 11, 33, 62, 46, 76, 12, 98, 18, 11, 52, 76, 51])

In [58]:
my_array.max()

98

In [59]:
my_array.min()

10

In [60]:
my_array.argmax()

24

In [61]:
my_array.argmin()

7

In [63]:
my_array.sort()
my_array

array([10, 11, 11, 12, 15, 18, 19, 22, 23, 28, 33, 44, 46, 50, 51, 52, 55,
       62, 68, 71, 76, 76, 79, 82, 84, 88, 90, 96, 97, 98])

In [65]:
np.flipud(my_array)

array([98, 97, 96, 90, 88, 84, 82, 79, 76, 76, 71, 68, 62, 55, 52, 51, 50,
       46, 44, 33, 28, 23, 22, 19, 18, 15, 12, 11, 11, 10])

In [80]:
my_array[-1: :-1]

array([98, 97, 96, 90, 88, 84, 82, 79, 76, 76, 71, 68, 62, 55, 52, 51, 50,
       46, 44, 33, 28, 23, 22, 19, 18, 15, 12, 11, 11, 10])

### Bracket Indexing and selection

In [66]:
my_array

array([10, 11, 11, 12, 15, 18, 19, 22, 23, 28, 33, 44, 46, 50, 51, 52, 55,
       62, 68, 71, 76, 76, 79, 82, 84, 88, 90, 96, 97, 98])

In [67]:
my_array[0]

10

In [68]:
my_array[1]

11

In [69]:
my_array[29]

98

In [70]:
my_array[-1]

98

In [71]:
my_array[-2]

97

In [72]:
my_array[0:5]

array([10, 11, 11, 12, 15])

In [73]:
my_array[0:10]

array([10, 11, 11, 12, 15, 18, 19, 22, 23, 28])

In [74]:
my_array[0:10:2]

array([10, 11, 15, 19, 23])

In [75]:
my_array

array([10, 11, 11, 12, 15, 18, 19, 22, 23, 28, 33, 44, 46, 50, 51, 52, 55,
       62, 68, 71, 76, 76, 79, 82, 84, 88, 90, 96, 97, 98])

In [78]:
my_array[-5:-1]

array([88, 90, 96, 97])

In [79]:
my_array[-1:-6:-1]

array([98, 97, 96, 90, 88])

### Broadcasting

In [82]:
top_five = my_array[0:5]
top_five

array([10, 11, 11, 12, 15])

In [84]:
top_five[ : ] = 2

In [85]:
top_five

array([2, 2, 2, 2, 2])

In [86]:
my_array

array([ 2,  2,  2,  2,  2, 18, 19, 22, 23, 28, 33, 44, 46, 50, 51, 52, 55,
       62, 68, 71, 76, 76, 79, 82, 84, 88, 90, 96, 97, 98])

In [96]:
my_array_2 = np.random.randint(10,100, size = 30)
my_array_2

array([26, 77, 98, 54, 60, 39, 62, 95, 37, 61, 34, 19, 31, 85, 21, 41, 87,
       65, 97, 21, 61, 21, 47, 73, 45, 92, 93, 27, 89, 28])

In [97]:
my_array_2.sort()

In [98]:
my_array_2

array([19, 21, 21, 21, 26, 27, 28, 31, 34, 37, 39, 41, 45, 47, 54, 60, 61,
       61, 62, 65, 73, 77, 85, 87, 89, 92, 93, 95, 97, 98])

In [99]:
my_copy_array = my_array_2.copy()
my_copy_array

array([19, 21, 21, 21, 26, 27, 28, 31, 34, 37, 39, 41, 45, 47, 54, 60, 61,
       61, 62, 65, 73, 77, 85, 87, 89, 92, 93, 95, 97, 98])

In [100]:
top_five = my_copy_array[0:5]
top_five

array([19, 21, 21, 21, 26])

In [101]:
top_five[ : ] = 3

top_five

array([3, 3, 3, 3, 3])

In [102]:
my_copy_array

array([ 3,  3,  3,  3,  3, 27, 28, 31, 34, 37, 39, 41, 45, 47, 54, 60, 61,
       61, 62, 65, 73, 77, 85, 87, 89, 92, 93, 95, 97, 98])

In [103]:
my_array_2

array([19, 21, 21, 21, 26, 27, 28, 31, 34, 37, 39, 41, 45, 47, 54, 60, 61,
       61, 62, 65, 73, 77, 85, 87, 89, 92, 93, 95, 97, 98])

### Indexing and selection for 2D arrays

In [104]:
my_reshaped_array_2

array([[ 2,  2,  2,  2,  2],
       [18, 19, 22, 23, 28],
       [33, 44, 46, 50, 51],
       [52, 55, 62, 68, 71],
       [76, 76, 79, 82, 84],
       [88, 90, 96, 97, 98]])

array[row][column] or array[row, column]

In [105]:
my_reshaped_array_2[0]

array([2, 2, 2, 2, 2])

In [106]:
my_reshaped_array_2[5]

array([88, 90, 96, 97, 98])

In [108]:
my_reshaped_array_2[ : , 0]

array([ 2, 18, 33, 52, 76, 88])

In [109]:
my_reshaped_array_2[3: ]

array([[52, 55, 62, 68, 71],
       [76, 76, 79, 82, 84],
       [88, 90, 96, 97, 98]])

In [110]:
my_reshaped_array_2[ : , 2: ]

array([[ 2,  2,  2],
       [22, 23, 28],
       [46, 50, 51],
       [62, 68, 71],
       [79, 82, 84],
       [96, 97, 98]])

In [112]:
my_reshaped_array_2[2:4 , 1:3]

array([[44, 46],
       [55, 62]])

In [111]:
my_reshaped_array_2

array([[ 2,  2,  2,  2,  2],
       [18, 19, 22, 23, 28],
       [33, 44, 46, 50, 51],
       [52, 55, 62, 68, 71],
       [76, 76, 79, 82, 84],
       [88, 90, 96, 97, 98]])

#### Fancy indexing

In [113]:
my_reshaped_array_2[ [5,3,1] ]

array([[88, 90, 96, 97, 98],
       [52, 55, 62, 68, 71],
       [18, 19, 22, 23, 28]])

In [114]:
my_reshaped_array_2[ : , [4,0,3]]

array([[ 2,  2,  2],
       [28, 18, 23],
       [51, 33, 50],
       [71, 52, 68],
       [84, 76, 82],
       [98, 88, 97]])

### Boolean selection

In [115]:
my_reshaped_array

array([[ 2,  2,  2,  2,  2, 18, 19, 22, 23, 28, 33, 44, 46, 50, 51],
       [52, 55, 62, 68, 71, 76, 76, 79, 82, 84, 88, 90, 96, 97, 98]])

In [116]:
my_reshaped_array > 60

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True]])

In [117]:
my_reshaped_array[my_reshaped_array > 60]

array([62, 68, 71, 76, 76, 79, 82, 84, 88, 90, 96, 97, 98])

In [118]:
filter_1 = my_reshaped_array > 60
filter_2 = my_reshaped_array < 90

In [120]:
my_reshaped_array[filter_1]

array([62, 68, 71, 76, 76, 79, 82, 84, 88, 90, 96, 97, 98])

In [121]:
my_reshaped_array[filter_2]

array([ 2,  2,  2,  2,  2, 18, 19, 22, 23, 28, 33, 44, 46, 50, 51, 52, 55,
       62, 68, 71, 76, 76, 79, 82, 84, 88])

In [119]:
my_reshaped_array[filter_1 & filter_2]

array([62, 68, 71, 76, 76, 79, 82, 84, 88])

In [122]:
my_reshaped_array[filter_1 | filter_2]

array([ 2,  2,  2,  2,  2, 18, 19, 22, 23, 28, 33, 44, 46, 50, 51, 52, 55,
       62, 68, 71, 76, 76, 79, 82, 84, 88, 90, 96, 97, 98])

### Arithmetic operations

In [123]:
my_list

[1, 2, 3, 4, 5]

In [133]:
arr = np.arange(0,10)

arr2 = np.arange(10,20)

In [125]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [134]:
arr.shape, arr2.shape

((10,), (10,))

In [127]:
my_list + my_list

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [135]:
arr + arr2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [137]:
my_list - my_list

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [138]:
arr2 - arr

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [139]:
my_list * my_list

TypeError: can't multiply sequence by non-int of type 'list'

In [140]:
arr2 * arr

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [141]:
arr2 * 4

array([40, 44, 48, 52, 56, 60, 64, 68, 72, 76])

In [142]:
my_list / my_list

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [143]:
arr2 / arr

C:\Users\LENOVO\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf, 11.        ,  6.        ,  4.33333333,  3.5       ,
        3.        ,  2.66666667,  2.42857143,  2.25      ,  2.11111111])

### Universal functions

In [144]:
np.sqrt(arr2)

array([3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894])

In [145]:
np.log(arr2)

array([2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [146]:
np.mod(arr2,2)

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [147]:
arr_copy = np.copy(arr)
arr_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [148]:
arr = np.zeros(5)

In [149]:
arr / arr

C:\Users\LENOVO\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan, nan, nan, nan, nan])

In [151]:
1/arr

C:\Users\LENOVO\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([inf, inf, inf, inf, inf])

In [152]:
arr = np.arange(5)

In [153]:
arr

array([0, 1, 2, 3, 4])

In [154]:
arr * 2

array([0, 2, 4, 6, 8])

In [155]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [156]:
arr[(arr % 3) == 0]

array([3, 6, 9])

In [157]:
arr = np.arange(30).reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [158]:
arr[0:2 , 4:6]

array([[ 4,  5],
       [10, 11]])

In [160]:
arr_copied = arr.copy().reshape(2,15)
arr_copied

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [162]:
arr_copied[ : , [7,4] ]

array([[ 7,  4],
       [22, 19]])

In [163]:
arr.mod(4)

AttributeError: 'numpy.ndarray' object has no attribute 'mod'

https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs